# Generated by Django 5.2.7 on 2025-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
