# Generated by Django 5.2.7 on 2025-11-06 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customproduct_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('rating', models.CharField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at:')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='products_pr_product_4b33ab_idx'), models.Index(fields=['user', 'product'], name='products_pr_user_id_44db7a_idx')],
            },
        ),
    ]
